# Eureka Server ??
server:
  port: 8761

# Eureka Server Name
spring:
  application:
    name: discoverservice

# Eureka Server ?? ??
eureka:
  client:
    register-with-eureka: false #Eureka Server? Client? ??? ??? ??? ???? ??? ??
    fetch-registry: false # Eureka Server? ??? ??? ???? ??